apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: conversao-temperatura
          image: nadilson/conversao-temperatura:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      nodePort: 32000
  type: LoadBalancer